import std.result.{Result}

let foo = Result.Err("test")